server {
    listen 80;
    server_name localhost;

    location /bank/ {
        alias /usr/share/nginx/html/bank/;
        index index.html;
        try_files $uri $uri/ /bank/index.html;
    }

    # 루트로 접속 시 /bank/로 리다이렉트 (선택 사항)
    location / {
        return 301 $scheme://$http_host/bank/;
    }
}
